apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
  namespace: default
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: nexus-a.kaholodemo.net/petclinic
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
